server:
  port: 8081
spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/gulimall_pms
    driver-class-name:  com.mysql.jdbc.Driver
mybatis-plus:
  mapper-locations: class-path:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
