spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gulimall_wms
    username: root
    password: 1234
mybatis-plus:
  mapper-locations: class-path:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 7000