spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gulimall_sms
    username: root
    password: 1234
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimail-coupon
mybatis-plus:
  mapper-locations:  class-path:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 8000
